- name: "Install Keepalived"
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: yes
  tags: install

- name: "Set net.ipv4.ip_forward=1 and net.ipv4.ip_nonlocal_bind=1"
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.ip_forward
    - net.ipv4.ip_nonlocal_bind
  tags: config

- name: "Create Keepalived configuration file"
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  tags: config

- name: "debug all var"
  ansible.builtin.debug:
    var: ha_keepalived_master_hostname
  tags: debug

- name: "Enable and start Keepalived"
  ansible.builtin.systemd:
    name: keepalived
    state: started
    enabled: yes
  tags: config
